### ISSUE TITLE
request email address

### ISSUE THREAD

**Issue by pyj8711** [Aiuan/OCULii_EAGLE_Decoder#1]

**Comment by Aiuan** [comment]
Hi

       My e-mail address: ***@***.***

 

发件人: ***@***.*** ***@***.***> 代表 pyj8711
发送时间: 2023年1月30日 15:16
收件人: Aiuan/OCULii_EAGLE_Decoder ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Aiuan/OCULii_EAGLE_Decoder] request email address (Issue #1)

 

Hi, could you please post your email address here? I want to consult you about some questions.

**Comment by Aiuan** [comment]
fyai@zju.edu.cn
